dars/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('posts.urls')),
    path('users/',include('users.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import RegisterView,LoginView,ProfileView,LogoutView,ProfileEditView,UserAllView,DeleteUserView,EditAllUserView

app_name="users"
urlpatterns = [
    path('register/',RegisterView.as_view(),name="register"),
    path('login/',LoginView.as_view(),name="login"),
    path('profile/',ProfileView.as_view(),name="profile"),
    path('logout/',LogoutView.as_view(),name="logout"),
    path('profile/edit/',ProfileEditView.as_view(),name="profile_edit"),
    path('all/',UserAllView.as_view(),name="all_user"),
    path('delete/<str:username>/',DeleteUserView.as_view(),name="delete_user"),
    path('edit/<str:username>/',EditAllUserView.as_view(),name="edit_user")

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.
class CustomUser(AbstractUser):
    user_img = models.ImageField(default='h.jpg',upload_to='users/')
    bio = models.TextField()

users/forms.py
from django import  forms
from django.contrib.auth.forms import AuthenticationForm

from users.models import CustomUser


class RegisterForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username','first_name','last_name','email','password')


    def save(self,commit=True):
        hash = super().save(commit)
        hash.set_password(self.cleaned_data['password'])
        hash.save()






class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'custom_username'}),
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'name': 'custom_password'}),
    )


class ProfileEditForm(forms.ModelForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'custom_username'}),
    )
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'custom_username'}),
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'custom_username'}),
    )

    class Meta:
        model = CustomUser
        fields = ('username','first_name','last_name','user_img',)


class EditProfileUsersForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username','first_name','last_name','email','is_superuser','user_img')

users/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View

from users.forms import RegisterForm, CustomAuthenticationForm, ProfileEditForm, EditProfileUsersForm
from users.models import CustomUser


# Create your views here.
class RegisterView(View):
    def get(self,request):
        user_form = RegisterForm()
        return render(request,'register.html',{"form":user_form})
    def post(self,request):
        user_form = RegisterForm(data=request.POST)
        if user_form.is_valid():
            user_form.save()
            return redirect("users:login")


class LoginView(View):
    def get(self,request):
        user_form = CustomAuthenticationForm()
        return render(request,'login.html',{"form":user_form})

    def post(self,request):
        user_form = CustomAuthenticationForm(data=request.POST)
        print(user_form)
        if user_form.is_valid():
            user = user_form.get_user()
            login(request,user)
            return redirect("posts:main")
        else:
            return render(request, 'login.html', {"form": user_form})

class LogoutView(View):
    def get(self,request):
        logout(request)
        return redirect("/")


class ProfileView(LoginRequiredMixin,View):
    def get(self,request):
        user = request.user
        context = {
            "user":user
        }

        return render(request,'profile.html',context)

class ProfileEditView(View):
    def get(self,request):
        user_form = ProfileEditForm(instance=request.user)
        context = {
            "form":user_form
        }

        return render(request,'profile-edit.html',context)

    def post(self,request):
        user_form = ProfileEditForm(instance=request.user,data=request.POST,files=request.FILES)
        if user_form.is_valid():
            user_form.save()
            return redirect("users:profile")
        else:
            context = {
                "form": user_form
            }

            return render(request, 'profile-edit.html', context)


class UserAllView(View):
    def get(self,request):
        users = CustomUser.objects.all()
        return render(request,'users.html',{"users":users})

class DeleteUserView(View):
    def get(self,request,username):
        user = CustomUser.objects.get(username=username)
        user.delete()
        return redirect("users:all_user")


class EditAllUserView(View):
    def get(self,request,username):
        custom = CustomUser.objects.get(username=username)
        users = EditProfileUsersForm(instance=custom)
        return render(request,'edit_users.html',{"form":users})
    def post(self,request,username):
        custom = CustomUser.objects.get(username=username)
        users = EditProfileUsersForm(instance=custom,data=request.POST,files=request.FILES)

        if users.is_valid():
            users.save()
            return redirect("users:all_user")
        else:
            return render(request, 'edit_users.html', {"form": users})

users/templates/delete_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

users/templates/edit_users.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="untree_co-section pb-0" id="home-section">
    <div class="container">
      <div class="row justify-content-center text-center">
        <div class="col-md-7">

                     <div class="custom-block" data-aos="fade-up" data-aos-delay="100">
                <h2 class="section-title text-black">Register</h2>
                <form class="contact-form" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

               {{ form.as_p }}


                  <button type="submit" class="btn btn-primary">edit</button>
                    <br>

                </form>
              </div> </div>
      </div>

    </div>
  </div>
{% endblock content %}

users/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="untree_co-section pb-0" id="home-section">
    <div class="container">
      <div class="row justify-content-center text-center">
        <div class="col-md-7">

                     <div class="custom-block" data-aos="fade-up" data-aos-delay="100">
                <h2 class="section-title text-black">Login</h2>
                <form class="contact-form" method="post">
{% csrf_token %}
                     <div class="form-group">
                    {{ form }}
                            </div>


                  <button type="submit" class="btn btn-primary">Login</button>
                    <br>
                    <span>Agarda ro'yxatdan o'tmagan bo'lsangiz <a href="{% url 'users:register' %}">linkni</a> bosing</span>
                </form>
              </div> </div>
      </div>

    </div>
  </div>
{% endblock content %}

users/templates/profile-edit.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="untree_co-section pb-0" id="home-section">
    <div class="container">
      <div class="row justify-content-center text-center">
        <div class="col-md-7">

                     <div class="custom-block" data-aos="fade-up" data-aos-delay="100">
                <h2 class="section-title text-black">Profile Edit</h2>
                <form class="contact-form" method="post" enctype="multipart/form-data">
{% csrf_token %}
                     <div class="form-group">
                    {{ form }}
                            </div>


                  <button type="submit" class="btn btn-outline-black w-100">Edit</button>
                    </form>
              </div> </div>
      </div>

    </div>
  </div>
{% endblock content %}

users/templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="untree_co-section pb-0" id="home-section">
<div class="container">
      <div class="portfolio-single-wrap unslate_co--section" id="portfolio-single-section">

        <div class="portfolio-single-inner">
          <h2 class="heading-portfolio-single-h2 text-black">Profile</h2>

          <div class="row mb-5 align-items-stretch">

            <div class="col-lg-6 mb-5 mb-lg-0">
              <img src="{{ user.user_img.url }}" alt="Image" class="img-fluid">
            </div>

            <div class="col-lg-6 pl-lg-5">
              <div class="row mb-3">
                <div class="col-sm-6 col-md-6 col-lg-6 mb-4">
                  <div class="detail-v1">
                    <span class="detail-label">Full name</span>
                    <span class="detail-val">{{ user.first_name }} {{ user.last_name }}</span>
                  </div>
                </div>
                <div class="col-sm-6 col-md-6 col-lg-6 mb-4">
                  <div class="detail-v1">
                    <span class="detail-label">Role</span>
                    <span class="detail-val"><a href="#">Identity</a>, <a href="#">Web Design</a></span>
                  </div>
                </div>
                <div class="col-sm-6 col-md-6 col-lg-6 mb-4">
                  <div class="detail-v1">
                    <span class="detail-label">Client</span>
                    <span class="detail-val">itpark-kagan.com</span>
                  </div>
                </div>
                <div class="col-sm-6 col-md-6 col-lg-6 mb-4">
                  <div class="detail-v1">
                    <span class="detail-label">Visit</span>
                    <span class="detail-val"><a href="https://untree.co">https://untree.co/</a></span>
                  </div>
                </div>
              </div>

              <h1>Bio</h1>
              <p>
                  {{ user.bio }}
              </p>
                <a href="{% url 'users:profile_edit' %}" class="btn btn-outline-black">Edit Profile <i class="fa-regular fa-pen-to-square"></i></a>

            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

users/templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="untree_co-section pb-0" id="home-section">
    <div class="container">
      <div class="row justify-content-center text-center">
        <div class="col-md-7">

                     <div class="custom-block" data-aos="fade-up" data-aos-delay="100">
                <h2 class="section-title text-black">Register</h2>
                <form class="contact-form" method="post">
                    {% csrf_token %}
                  <div class="row">
                    <div class="col-md-6">
                      <div class="form-group">
                        <label class="" for="fname">First name</label>
                        <input name="first_name" type="text" class="form-control" id="fname">
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        <label class="" for="lname">Last name</label>
                        <input name="last_name" type="text" class="form-control" id="lname">
                      </div>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="" for="email">Email address</label>
                    <input name="email" type="email" class="form-control" id="email" aria-describedby="emailHelp">
                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                  </div>
                     <div class="form-group">
                    <label class="" for="email">Username</label>
                    <input name="username" type="text" class="form-control">
                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                  </div>
                  <div class="form-group">
                    <label class="" for="password">Password</label>
                    <input name="password" type="password" class="form-control" id="password">
                  </div>


                  <button type="submit" class="btn btn-primary">Register</button>
                    <br>
                    <span>Agarda ro'yxatdan o'tgan bo'lsangiz <a href="{% url 'users:login' %}">linkni</a> bosing</span>
                </form>
              </div> </div>
      </div>

    </div>
  </div>
{% endblock content %}

users/templates/users.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="untree_co-section pb-0" id="home-section">
<div class="container">
<h1>Userlar Ro'yxati</h1>
     <div class="row">
         <div class="col">
            <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First</th>
      <th scope="col">Last</th>
      <th scope="col">username</th>
      <th scope="col">email</th>
      <th scope="col">actions</th>
    </tr>
  </thead>
  <tbody>
  {% for user in users %}
    <tr>
      <th scope="row">{{ user.id }}</th>
      <td>{{ user.first_name }}</td>
      <td>{{ user.last_name }}</td>
      <td>@{{ user.username }}</td>
      <td>@{{ user.email }}</td>
      <td>
          <div class="btn-group">
              <a href="{% url 'users:edit_user' user.username %}" class="btn btn-primary">edit</a>
              <a href="{% url 'users:delete_user' user.username %}" class="btn btn-danger">remove</a>
          </div>
      </td>
    </tr>
  {% endfor %}
  </tbody>
</table>
         </div>
     </div>
    </div>
  </div>
{% endblock content %}