dars/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('posts.urls')),
    path('users/',include('users.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import landing,DetailView,AddCourseView,LessonAddView,AddFullCourseView

app_name="posts"
urlpatterns = [
    path('',landing,name="main"),
    path('detail/<uuid:id>/',DetailView.as_view(),name="detail"),
    path('add/',AddCourseView.as_view(),name="add_course"),
    path('lesson/',LessonAddView.as_view(),name="lesson"),
    path('complete/',AddFullCourseView.as_view(),name="add_full")
]

users/urls.py
from django.urls import path
from .views import RegisterView,LoginView,ProfileView,LogoutView,ProfileEditView,UserAllView,DeleteUserView,EditAllUserView

app_name="users"
urlpatterns = [
    path('register/',RegisterView.as_view(),name="register"),
    path('login/',LoginView.as_view(),name="login"),
    path('profile/',ProfileView.as_view(),name="profile"),
    path('logout/',LogoutView.as_view(),name="logout"),
    path('profile/edit/',ProfileEditView.as_view(),name="profile_edit"),
    path('all/',UserAllView.as_view(),name="all_user"),
    path('delete/<str:username>/',DeleteUserView.as_view(),name="delete_user"),
    path('edit/<str:username>/',EditAllUserView.as_view(),name="edit_user")

]

posts/models.py
import uuid

from django.db import models

from users.models import CustomUser


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return  self.name

class Product(models.Model):
    id = models.UUIDField(unique=True, default=uuid.uuid4, editable=False, primary_key=True)
    title = models.CharField(max_length=150)
    author = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='product/')
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.title} uuid:{self.id}"



class Lesson(models.Model):
    id = models.UUIDField(unique=True, default=uuid.uuid4, editable=False, primary_key=True)
    title=models.CharField(max_length=150)
    url = models.TextField()

    def __str__(self):
        return self.title


class Video(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    video_url = models.ForeignKey(Lesson,on_delete=models.CASCADE)


    def __str__(self):
        return self.product.title

class Comment(models.Model):
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE,related_name='product')
    comment= models.TextField()


class Services(models.Model):
    img = models.ImageField(upload_to='services')
    title = models.CharField(max_length=100)
    description = models.TextField()

class MyBlog(models.Model):
    img = models.ImageField(upload_to='blog/')
    title = models.CharField()
    descr = models.TextField()

    def __str__(self):
        return self.title

templates/add_course.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="untree_co-section pb-0" id="home-section">
    <div class="container">
        Step:1
      <div class="row justify-content-center text-center">
        <div class="col-md-7">

                     <div class="custom-block" data-aos="fade-up" data-aos-delay="100">
                <h2 class="section-title text-black">Add Course</h2>
                <form class="contact-form" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

               {{ form.as_p }}


                  <button type="submit" class="btn btn-primary">next</button>
                    <br>

                </form>
              </div> </div>
      </div>

    </div>
  </div>
{% endblock content %}

templates/addfull.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="untree_co-section pb-0" id="home-section">
    <div class="container">
        Step:3
      <div class="row justify-content-center text-center">
        <div class="col-md-7">

                     <div class="custom-block" data-aos="fade-up" data-aos-delay="100">
                <h2 class="section-title text-black">for end</h2>
                <form class="contact-form" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

               {{ form.as_p }}


                  <button type="submit" class="btn btn-primary">next</button>
                    <br>

                </form>
              </div> </div>
      </div>

    </div>
  </div>
{% endblock content %}

templates/base.html
{% load static %}
<!Doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="author" content="Untree.co">
  <link rel="shortcut icon" href="favicon.png">

  <meta name="description" content="" />
  <meta name="keywords" content="" />

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&family=PT+Mono&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/jquery.fancybox.min.css' %}">
  <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
  <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">
  <link rel="stylesheet" href="{% static 'css/aos.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <title>Minimal Free HTML Template by Untree.co</title>
</head>
<body data-spy="scroll" data-target=".site-navbar-target" data-offset="100">

  <div class="lines-wrap">
    <div class="lines-inner">
      <div class="lines"></div>
    </div>
  </div>
  <!-- END lines -->

  <div class="site-mobile-menu site-navbar-target">
    <div class="site-mobile-menu-header">
      <div class="site-mobile-menu-close">
        <span class="icofont-close js-menu-toggle"></span>
      </div>
    </div>
    <div class="site-mobile-menu-body"></div>
  </div>

  <nav class="site-nav dark mb-5 site-navbar-target">
    <div class="container">
      <div class="site-navigation">
        <a href="{% url 'posts:main' %}" class="logo m-0">IT PARK<span class="text-primary">.</span></a>

        <ul class="js-clone-nav d-none d-lg-inline-none site-menu float-right site-nav-wrap">
          <li><a href="#home-section" class="nav-link active">Home</a></li>
          <li><a href="#portfolio-section" class="nav-link">Kurslar</a></li>
          <li class="has-children">
            <a href="#about-section" class="nav-link">Biz Haqimizda</a>
            <ul class="dropdown">
              <li><a href="elements.html" class="nav-link"></a></li>
              <li class="has-children">
                <a href="#">Menu Two</a>
                <ul class="dropdown">
                  <li><a href="#" class="nav-link">Sub Menu One</a></li>
                  <li><a href="#" class="nav-link">Sub Menu Two</a></li>
                  <li><a href="#" class="nav-link">Sub Menu Three</a></li>
                </ul>
              </li>
              <li><a href="#" class="nav-link">Menu Three</a></li>
            </ul>
          </li>
          <li><a href="#services-section" class="nav-link">Services</a></li>

          <li><a href="#contact-section" class="nav-link">Contact us</a></li>
        {% if request.user.is_superuser %}
          <li><a href="{% url 'users:all_user' %}" class="nav-link btn btn-outline-black my-2">Users</a></li>
          <li><a href="{% url 'posts:add_course' %}" class="nav-link btn btn-outline-black my-2">Add Course</a></li>
            <li><a href="#contact-section" class="nav-link btn btn-outline-black my-2">Edit Course</a></li>

        {% endif %}
            {% if request.user.is_authenticated %}
                  <li><a href="{% url 'users:profile' %}" class="nav-link btn btn-outline-black my-2">Profile</a></li>
                 <li><a href="{% url 'users:logout' %}" class="nav-link btn btn-danger text-light">logout</a></li>

        {% else %}
                  <li><a href="{% url 'users:login' %}" class="nav-link btn btn-outline-black">Login</a></li>

            {% endif %}
        </ul>

        <a href="#" class="burger ml-auto float-right site-menu-toggle js-menu-toggle d-inline-block d-lg-inline-block" data-toggle="collapse" data-target="#main-navbar">
          <span></span>
        </a>

      </div>
    </div>
  </nav>


      {% block content %}

  {% endblock content %}



    <div class="site-footer">
      <div class="container">

        <div class="row">
          <div class="col-lg-3">
            <div class="widget">
              <h3>Home</h3>
              <ul class="list-unstyled float-left links">
                <li><a href="#">Untree.co</a></li>
                <li><a href="#">About us</a></li>
                <li><a href="#">Projects</a></li>
                <li><a href="#">Services</a></li>
                <li><a href="#">Terms</a></li>
                <li><a href="#">Privacy</a></li>
              </ul>
            </div> <!-- /.widget -->
          </div> <!-- /.col-lg-3 -->

          <div class="col-lg-3">
            <div class="widget">
              <h3>Projects</h3>
              <ul class="list-unstyled float-left links">
                <li><a href="#">HTML5</a></li>
                <li><a href="#">CSS3</a></li>
                <li><a href="#">Untree.co</a></li>
                <li><a href="#">Free Templates</a></li>
                <li><a href="#">WordPress Themes</a></li>
              </ul>
            </div> <!-- /.widget -->
          </div> <!-- /.col-lg-3 -->

          <div class="col-lg-3">
            <div class="widget">
              <h3>Services</h3>
              <ul class="list-unstyled float-left links">
                <li><a href="#">Untree.co</a></li>
                <li><a href="#">jQuery</a></li>
                <li><a href="#">Bootstrap</a></li>
                <li><a href="#">Freebies</a></li>
              </ul>
            </div> <!-- /.widget -->
          </div> <!-- /.col-lg-3 -->


          <div class="col-lg-3">
            <div class="widget">
              <h3>Contact</h3>
              <address>43 Raymouth Rd. Baltemoer, London 3910</address>
              <ul class="list-unstyled links mb-4">
                <li><a href="tel://11234567890">+1(123)-456-7890</a></li>
                <li><a href="tel://11234567890">+1(123)-456-7890</a></li>
                <li><a href="mailto:info@mydomain.com">info@mydomain.com</a></li>
              </ul>

              <h3>Connect</h3>
              <ul class="list-unstyled social">
                <li><a href="#"><span class="icon-instagram"></span></a></li>
                <li><a href="#"><span class="icon-twitter"></span></a></li>
                <li><a href="#"><span class="icon-facebook"></span></a></li>
                <li><a href="#"><span class="icon-linkedin"></span></a></li>
                <li><a href="#"><span class="icon-pinterest"></span></a></li>
                <li><a href="#"><span class="icon-dribbble"></span></a></li>
              </ul>

            </div> <!-- /.widget -->
          </div> <!-- /.col-lg-3 -->

        </div> <!-- /.row -->





        <div class="row mt-5">
          <div class="col-12 text-center">
            <!--
              **==========
              NOTE:
              Please don't remove this copyright link unless you buy the license here https://untree.co/license/

              **==========
            -->
            <p class="mb-0">Copyright &copy;<script>document.write(new Date().getFullYear());</script>. All Rights Reserved. &mdash; Designed with love by <a href="https://untree.co">Untree.co</a>  Distributed By <a href="https://themewagon.com">ThemeWagon</a> <!-- License information: https://untree.co/license/ -->
            </p>
          </div>
        </div>
      </div> <!-- /.container -->
    </div> <!-- /.site-footer -->

    <div id="overlayer"></div>
    <div class="loader">
      <div class="spinner-border" role="status">
        <span class="sr-only">Loading...</span>
      </div>
    </div>

    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/jquery.fancybox.min.js' %}"></script>
    <script src="{% static 'js/aos.js' %}"></script>
    <script src="{% static 'js/wave-animate.js' %}"></script>
    <script src="{% static 'js/circle-progress.js' %}"></script>
    <script src="{% static 'js/imagesloaded.pkgd.js' %}"></script>
    <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
    <script src="{% static 'js/TweenMax.min.js' %}"></script>
    <script src="{% static 'js/ScrollMagic.min.js' %}"></script>
    <script src="{% static 'js/scrollmagic.animation.gsap.min.js' %}"></script>


    <script src="{% static 'js/custom.js'  %}"></script>

  </body>
</html>

templates/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="untree_co-section untree_co-section-4 pb-0"  id="portfolio-section">
    <div class="container">
      <div class="portfolio-single-wrap unslate_co--section" id="portfolio-single-section">

        <div class="portfolio-single-inner">
          <h2 class="heading-portfolio-single-h2 text-black">{{ product.title }} Dars</h2>

          <div class="row justify-content-between mb-5">
            <div class="col-12 mb-4">
              <div class="owl-carousel single-slider">
                <figure class="mb-4">
                  <img src="images/portfolio_1.jpg" alt="Image" class="img-fluid">
                </figure>
                <figure class="mb-4">
                  <img src="images/portfolio_2.jpg" alt="Image" class="img-fluid">
                </figure>
              </div>
            </div>
            <div class="col-12 my-5">
              <div class="row">
                <div class="col-sm-6 col-md-6 col-lg-3">
                  <div class="detail-v1">
                    <span class="detail-label">Project Date</span>
                    <span class="detail-val">{{ product.created_at }}</span>
                  </div>
                </div>
                <div class="col-sm-6 col-md-6 col-lg-3">
                  <div class="detail-v1">
                    <span class="detail-label">Category</span>
                    <span class="detail-val"><a href="#">{{ product.category }}</a></span>
                  </div>
                </div>
                <div class="col-sm-6 col-md-6 col-lg-3">
                  <div class="detail-v1">
                    <span class="detail-label">Client</span>
                    <span class="detail-val">Untree.co</span>
                  </div>
                </div>
                <div class="col-sm-6 col-md-6 col-lg-3">
                  <div class="detail-v1">
                    <span class="detail-label">Visit</span>
                    <span class="detail-val"><a href="https://untree.co">https://untree.co/</a></span>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-6">
                <img src="{{ product.image.url }}" class="img-thumbnail" alt="">
            </div>
            <div class="col-md-6">
                <h4>dars haqida</h4>
             <p>
                 {{ product.description }}

             </p>
                <p>
                    Dasrlar Soni:{{ product.video_set.count }}ta
                </p>
              </div>
              
              <div class="col-12">
                  {% for course in product.video_set.all %}
       <div id="accordion">
        <div class="card">
            <div class="card-header" id="section1">
                <h5 class="mb-0">
                    <button class="btn btn-link" data-toggle="collapse" data-target="#collapse1" aria-expanded="true" aria-controls="collapse1">
                        {{ course.video_url.title }}
                    </button>
                </h5>
            </div>

            <div id="collapse1" class="collapse show" aria-labelledby="section1" data-parent="#accordion">
                <div class="card-body">
                    <video width="100%" controls src="{{ course.video_url.url }}"></video>
                </div>
            </div>
        </div>



        <!-- Add more sections as needed -->

    </div>
                  {% endfor %}
              </div>

          </div>

        </div>
      </div>
    </div>
  </div>


{% endblock content %}

templates/lesson.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="untree_co-section pb-0" id="home-section">
    <div class="container">
        <p>Step:2</p>
      <div class="row justify-content-center text-center">
        <div class="col-md-7">

                     <div class="custom-block" data-aos="fade-up" data-aos-delay="100">
                <h2 class="section-title text-black">Lesson number</h2>
                <form class="contact-form" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

               {{ form.as_p }}


                  <button type="submit" class="btn btn-primary">next</button>
                    <br>

                </form>
              </div> </div>
      </div>

    </div>
  </div>
{% endblock content %}

templates/portfolio-single-1.html
<!-- /*
* Template Name: Minimal
* Template Author: Untree.co
* Author URI: https://untree.co/
* License: https://creativecommons.org/licenses/by/3.0/
*/ -->
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="author" content="Untree.co">
  <link rel="shortcut icon" href="favicon.png">

  <meta name="description" content="" />
  <meta name="keywords" content="" />

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&family=PT+Mono&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="css/bootstrap.min.css">
  <link rel="stylesheet" href="css/owl.carousel.min.css">
  <link rel="stylesheet" href="css/owl.theme.default.min.css">
  <link rel="stylesheet" href="css/jquery.fancybox.min.css">
  <link rel="stylesheet" href="fonts/icomoon/style.css">
  <link rel="stylesheet" href="fonts/flaticon/font/flaticon.css">
  <link rel="stylesheet" href="css/aos.css">
  <link rel="stylesheet" href="css/style.css">

  <title>Minimal Free HTML Template by Untree.co</title>
</head>

<body data-spy="scroll" data-target=".site-navbar-target" data-offset="100">


  <div class="site-mobile-menu site-navbar-target">
    <div class="site-mobile-menu-header">
      <div class="site-mobile-menu-close">
        <span class="icofont-close js-menu-toggle"></span>
      </div>
    </div>
    <div class="site-mobile-menu-body"></div>
  </div>
  
  <nav class="site-nav dark mb-5 site-navbar-target">
    <div class="container">
      <div class="site-navigation">
        <a href="index.html" class="logo m-0">Space<span class="text-primary">.</span></a>

        <ul class="js-clone-nav d-none d-lg-inline-none site-menu float-right">
          <li><a href="#home-section" class="nav-link active">Home</a></li>
          <li><a href="#portfolio-section">Portfolio</a></li>

          <li class="has-children">
            <a href="#about-section">About</a>
            <ul class="dropdown">
              <li><a href="elements.html">Elements</a></li>
              <li class="has-children">
                <a href="#">Menu Two</a>
                <ul class="dropdown">
                  <li><a href="#">Sub Menu One</a></li>
                  <li><a href="#">Sub Menu Two</a></li>
                  <li><a href="#">Sub Menu Three</a></li>
                </ul>
              </li>
              <li><a href="#">Menu Three</a></li>
            </ul>
          </li>
          <li><a href="services.html">Services</a></li>
          <li><a href="contact.html">Contact us</a></li>
        </ul>

        <a href="#" class="burger ml-auto float-right site-menu-toggle js-menu-toggle d-inline-block d-lg-inline-block" data-toggle="collapse" data-target="#main-navbar">
          <span></span>
        </a>

      </div>
    </div>
  </nav>



  


  <div class="untree_co-section untree_co-section-4 pb-0"  id="portfolio-section">
    <div class="container">
      <div class="portfolio-single-wrap unslate_co--section" id="portfolio-single-section">

        <div class="portfolio-single-inner">
          <h2 class="heading-portfolio-single-h2 text-black">Slider Portfolio Details</h2>

          <div class="row justify-content-between mb-5">
            <div class="col-12 mb-4">
              <div class="owl-carousel single-slider">
                <figure class="mb-4">
                  <img src="images/portfolio_1.jpg" alt="Image" class="img-fluid">
                </figure>
                <figure class="mb-4">
                  <img src="images/portfolio_2.jpg" alt="Image" class="img-fluid">
                </figure>
              </div>
            </div>
            <div class="col-12 my-5">
              <div class="row">
                <div class="col-sm-6 col-md-6 col-lg-3">
                  <div class="detail-v1">
                    <span class="detail-label">Project Date</span>
                    <span class="detail-val">March 9th, 2020</span>
                  </div>
                </div>
                <div class="col-sm-6 col-md-6 col-lg-3">
                  <div class="detail-v1">
                    <span class="detail-label">Role</span>
                    <span class="detail-val"><a href="#">Identity</a>, <a href="#">Web Design</a></span>
                  </div>
                </div>
                <div class="col-sm-6 col-md-6 col-lg-3">
                  <div class="detail-v1">
                    <span class="detail-label">Client</span>
                    <span class="detail-val">Untree.co</span>
                  </div>
                </div>
                <div class="col-sm-6 col-md-6 col-lg-3">
                  <div class="detail-v1">
                    <span class="detail-label">Visit</span>
                    <span class="detail-val"><a href="https://untree.co">https://untree.co/</a></span>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
            </div>
            <div class="col-md-6">
              <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.</p>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>


  <div class="site-footer">
    <div class="container">

      <div class="row">
        <div class="col-lg-3">
          <div class="widget">
            <h3>Home</h3>
            <ul class="list-unstyled float-left links">
              <li><a href="#">Untree.co</a></li>
              <li><a href="#">About us</a></li>
              <li><a href="#">Projects</a></li>
              <li><a href="#">Services</a></li>
              <li><a href="#">Terms</a></li>
              <li><a href="#">Privacy</a></li>
            </ul>
          </div> <!-- /.widget -->
        </div> <!-- /.col-lg-3 -->

        <div class="col-lg-3">
          <div class="widget">
            <h3>Projects</h3>
            <ul class="list-unstyled float-left links">
              <li><a href="#">HTML5</a></li>
              <li><a href="#">CSS3</a></li>
              <li><a href="#">Untree.co</a></li>
              <li><a href="#">Free Templates</a></li>
              <li><a href="#">WordPress Themes</a></li>
            </ul>
          </div> <!-- /.widget -->
        </div> <!-- /.col-lg-3 -->

        <div class="col-lg-3">
          <div class="widget">
            <h3>Services</h3>
            <ul class="list-unstyled float-left links">
              <li><a href="#">Untree.co</a></li>
              <li><a href="#">jQuery</a></li>
              <li><a href="#">Bootstrap</a></li>
              <li><a href="#">Freebies</a></li>
            </ul>
          </div> <!-- /.widget -->
        </div> <!-- /.col-lg-3 -->


        <div class="col-lg-3">
          <div class="widget">
            <h3>Contact</h3>
            <address>43 Raymouth Rd. Baltemoer, London 3910</address>
            <ul class="list-unstyled links mb-4">
              <li><a href="tel://11234567890">+1(123)-456-7890</a></li>
              <li><a href="tel://11234567890">+1(123)-456-7890</a></li>
              <li><a href="mailto:info@mydomain.com">info@mydomain.com</a></li>
            </ul>

            <h3>Connect</h3>
            <ul class="list-unstyled social">
              <li><a href="#"><span class="icon-instagram"></span></a></li>
              <li><a href="#"><span class="icon-twitter"></span></a></li>
              <li><a href="#"><span class="icon-facebook"></span></a></li>
              <li><a href="#"><span class="icon-linkedin"></span></a></li>
              <li><a href="#"><span class="icon-pinterest"></span></a></li>
              <li><a href="#"><span class="icon-dribbble"></span></a></li>
            </ul>

          </div> <!-- /.widget -->
        </div> <!-- /.col-lg-3 -->

      </div> <!-- /.row -->





      <div class="row mt-5">
        <div class="col-12 text-center">
          <p class=" mb-0">&copy; 2020. All Rights Reserved. Design by <a href="https://untree.co/" target="_blank" class=""><strong>Untree.co</strong></a> Distributed By <a href="https://themewagon.com">ThemeWagon</a> </p>
          <p class="">
            <span class="mx-2">Twitter <a href="https://twitter.com/untree_co">@Untree_co</a></span>
            <span>&bullet;</span>
            <span class="mx-2">Facebook <a href="https://web.facebook.com/Untree.co">@Untree.co</a></span>
          </p>

        </div>
      </div>
    </div> <!-- /.container -->
  </div> <!-- /.site-footer -->

  <script src="js/jquery-3.4.1.min.js"></script>
  <script src="js/popper.min.js"></script>
  <script src="js/bootstrap.min.js"></script>
  <script src="js/owl.carousel.min.js"></script>
  <script src="js/jquery.animateNumber.min.js"></script>
  <script src="js/jquery.waypoints.min.js"></script>
  <script src="js/jquery.fancybox.min.js"></script>
  <script src="js/aos.js"></script>
  <script src="js/wave-animate.js"></script>
  <script src="js/circle-progress.js"></script>
  <script src="js/imagesloaded.pkgd.js"></script>
  <script src="js/isotope.pkgd.min.js"></script>
  <script src="js/jquery.easing.1.3.js"></script>
  <script src="js/TweenMax.min.js"></script>
  <script src="js/ScrollMagic.min.js"></script>
  <script src="js/scrollmagic.animation.gsap.min.js"></script>

  <script src="js/custom.js"></script>
  
</body>

</html>

templates/video-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>